version: '3.4'

services:
  db:
      container_name: db
      environment:
          SA_PASSWORD: "root@123"
          ACCEPT_EULA: "Y"
          MSSQL_PID: Developer
      restart: always
      ports:
        - "1433:1433"
  shopping:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
        - db
    ports:
        - "8000:80"