apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping
  template:
    metadata:
      labels:
        app: shopping
    spec:
      containers:
      - name: shopping
        image: csaymandocker/shopping:latest
        ports:
        - containerPort: 8080
        env:
           - name: "ASPNETCORE_ENVIRONMENT"
             value: "Staging"
           - name: "Urls"
             value: "http://*:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: shopping
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: shopping  